-- MySQL Script generated by MySQL Workbench
-- Fri Sep 29 20:35:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Успеваемость
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Успеваемость
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Успеваемость` DEFAULT CHARACTER SET utf8 ;
USE `Успеваемость` ;

-- -----------------------------------------------------
-- Table `Успеваемость`.`Преподаватели`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Успеваемость`.`Преподаватели` (
  `ТабельныйНомер` VARCHAR(6) NOT NULL,
  `Фамилия` VARCHAR(45) NOT NULL,
  `Имя` VARCHAR(45) NOT NULL,
  `ФамилияИО` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ТабельныйНомер`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Успеваемость`.`Группы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Успеваемость`.`Группы` (
  `НомерГруппы` VARCHAR(10) NOT NULL,
  `Куратор` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`НомерГруппы`),
  INDEX `fk_Группы_Преподаватели1_idx` (`Куратор` ASC) VISIBLE,
  CONSTRAINT `fk_Группы_Преподаватели1`
    FOREIGN KEY (`Куратор`)
    REFERENCES `Успеваемость`.`Преподаватели` (`ТабельныйНомер`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Успеваемость`.`Студенты`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Успеваемость`.`Студенты` (
  `НомерЗачетки` VARCHAR(6) NOT NULL,
  `Группа` VARCHAR(10) NOT NULL,
  `Фамилия` VARCHAR(45) NOT NULL,
  `Имя` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`НомерЗачетки`),
  INDEX `fk_Студенты_Группы_idx` (`Группа` ASC) VISIBLE,
  CONSTRAINT `fk_Студенты_Группы`
    FOREIGN KEY (`Группа`)
    REFERENCES `Успеваемость`.`Группы` (`НомерГруппы`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Успеваемость`.`Предметы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Успеваемость`.`Предметы` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Название` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Успеваемость`.`Оценки`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Успеваемость`.`Оценки` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Студент` VARCHAR(6) NOT NULL,
  `Преподаватель` VARCHAR(6) NOT NULL,
  `Предметы` INT NOT NULL,
  `Оценка` INT NOT NULL,
  `Дата` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Оценки_Студенты1_idx` (`Студент` ASC) VISIBLE,
  INDEX `fk_Оценки_Преподаватели1_idx` (`Преподаватель` ASC) VISIBLE,
  INDEX `fk_Оценки_Предметы1_idx` (`Предметы` ASC) VISIBLE,
  CONSTRAINT `fk_Оценки_Студенты1`
    FOREIGN KEY (`Студент`)
    REFERENCES `Успеваемость`.`Студенты` (`НомерЗачетки`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Оценки_Преподаватели1`
    FOREIGN KEY (`Преподаватель`)
    REFERENCES `Успеваемость`.`Преподаватели` (`ТабельныйНомер`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Оценки_Предметы1`
    FOREIGN KEY (`Предметы`)
    REFERENCES `Успеваемость`.`Предметы` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Успеваемость`.`Преподаваемые предметы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Успеваемость`.`Преподаваемые предметы` (
  `Преподаватель` VARCHAR(6) NOT NULL,
  `Предмет` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_Преподаватели_has_Предметы_Пред_idx` (`Предмет` ASC) VISIBLE,
  INDEX `fk_Преподаватели_has_Предметы_Преп_idx` (`Преподаватель` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Преподаватели_has_Предметы_Препо1`
    FOREIGN KEY (`Преподаватель`)
    REFERENCES `Успеваемость`.`Преподаватели` (`ТабельныйНомер`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Преподаватели_has_Предметы_Предм1`
    FOREIGN KEY (`Предмет`)
    REFERENCES `Успеваемость`.`Предметы` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
